name: 'Terraform Apply'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Authenticate to Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/account.json
        gcloud auth activate-service-account --key-file=/tmp/account.json
        gcloud config set project ${{ secrets.TF_VAR_project_id }}

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan -out=tfplan

    - name: Apply Terraform
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
